name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main  # Ou a branch que você utiliza como principal

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use a versão do Node.js compatível com o Docusaurus

      - name: Install Dependencies
        run: npm install

      - name: Build Docusaurus Site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          keep_files: true
